title: Basharul Alam Mazu
logo: img/header_img.png
description: 
## Contact Information
- **Email:** [basharulalam6@gmail.com](mailto:basharulalam6@gmail.com)
- **LinkedIn:** [Basharul Alam Mazu](https://www.linkedin.com/in/basharul-alam-mazu-361464267/)
- **WhatsApp:** [Contact Me](https://wa.me/+8801813890622)
show_downloads: false
theme: jekyll-theme-minimal
